config/routes.rb
Rails.application.routes.draw do
  root 'top#top'
  get 'top/main'
  get 'top/logout'
  get 'cafes/show'
  get 'get_image/:id', to: 'cafes#get_image'
  post 'top/login'
  resources :users
  resources :cafes, only: [:create, :new, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
    #cafesテーブルから中間テーブルに対する関連付け
    has_many :cafe_tag_relations, dependent: :destroy
    #cafesテーブルから中間テーブルを介してTagsテーブルへの関連付け
    has_many :tags, through: :cafe_tag_relations, dependent: :destroy
    
    geocoded_by :address
    after_validation :geocode
end

app/models/cafe_tag_relation.rb
class CafeTagRelation < ApplicationRecord
  belongs_to :cafe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    #Tagsテーブルから中間テーブルに対する関連付け
    has_many :cafe_tag_relations, dependent: :destroy
    #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
    has_many :cafes, through: :cafe_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, uniqueness: true
  validates :password, presence: true, confirmation: true
  
  attr_accessor :password, :password_confirmation

  def password=(val)
   if val.present?
      self.pass = BCrypt::Password.create(val)
   end
   @password = val
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  def index
    @cafes = Cafe.order(created_at: :desc)#投稿順表示

    
    if params[:tag_ids]
      @cafes = []
      params[:tag_ids].each do |key, value|      
        @cafes += Tag.find_by(tag_name: key).cafes if value == "1"
      end
      @cafes.uniq!
    end
    
    if params[:tag]
      Tag.create(tag_name: params[:tag])
    end


  end

  def new
    @cafe = Cafe.new
  end

  def create
    @cafe = Cafe.new(name: params[:cafe][:name],message: params[:cafe][:message],image: params[:cafe][:image].read)
    if @cafe.save
      redirect_to root_path
    else
    redirect_to 'new'
    end
  end
  
  
  def get_image
    cafe = Cafe.find(params[:id])
    send_data cafe.image, disposition: :inline, type:'image/png'
  end

  def edit
   @cafe = Cafe.find(params[:id])
  end
  
  def destroy
    @cafe = Cafe.find(params[:id])
    @cafe.destroy
    redirect_to request.referer
  end
  
  def update
    @cafe = Cafe.find(params[:id])
    if @cafe.update(name: params[:cafe][:name],message: params[:cafe][:message],image: params[:cafe][:image].read)
       @cafe.save
       redirect_to'/'
    else
      render :new
    end
  end
  
  def show
    @cafe = Cafe.all
  end
  
  def cafe_params
      params.require(:cafe).permit(:lat,:lng)
  end
  
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render 'login'
  end

  def login
    user = User.find_by(uid: params[:uid])
    if user and BCrypt::Password.new(user.pass) == params[:pass]
      session[:login_uid] = user.uid
      redirect_to root_path
    else
      render 'login'
    end
  end

  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
  
  def top
    @cafe = Cafe.all
  end
  
  def destroy
    cafe = Cafe.find(params[:id])
    cafe.destroy
    redirect_to cafe_path
  end
  
  def cafe_params
      params.require(:cafe).permit(:lat,:lng)
  end
  
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(uid: params[:user][:uid], 
    password: params[:user][:password],
    password_confirmation: params[:user][:password_confirmation])
    if @user.valid? #validatesを実行してくれる
      flash[:notice] = 'userを追加しました'
      @user.pass = BCrypt::Password.create(params[:user][:password])
      @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(uid: params[:user][:uid], 
    password: params[:user][:password],
    password_confirmation: params[:user][:password_confirmation])
    if @user.valid? #validatesを実行してくれる
      flash[:notice] = 'userを追加しました'
      @user.pass = BCrypt::Password.create(params[:user][:password])
      @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cafes/create.html.erb
<h1>Cafes#create</h1>
<p>Find me in app/views/cafes/create.html.erb</p>

app/views/cafes/destroy.html.erb
<h1>Cafes#destroy</h1>
<p>Find me in app/views/cafes/destroy.html.erb</p>

app/views/cafes/edit.html.erb
<h1>編集ページ</h1>
<%= form_for @cafe, url:{action: :update} do |f| %>
<p>
  <%= f.label :name, '店名' %>
  <%= f.text_field :name %>
<br>
  <%= f.label :message, '説明' %>
  <%= f.text_area :message,:size=>"60x10" %>
<br>
  <%= f.label :image,'画像' %>
  <%= f.file_field :image %>
</p>
<!--タグ付け機能-->
  <div class='form-group'>
       <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |tag| %>
          <div class='form-check'>
              <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
              <% end %>
          </div>
      <% end %>
  </div>

  <%= f.submit "更新"%>

<% end %>

app/views/cafes/index.html.erb
<p>cafe index</p>


<%= link_to "戻る", :back %>

app/views/cafes/new.html.erb
<!DOCTYPE html>
<html>
  <header>
  	<h1 class="headline">
      <a>cafe巡り</a>
    </h1>
  <div class="right">
  <body>
  <p class='login'>
  <% if session[:login_uid] %>
    <%= link_to 'ログアウト', top_logout_path, class:'link' %>
    <%= link_to '投稿する', new_cafe_path, class:'link' %>
    <%= link_to 'マイページ', cafes_show_path, class:'link' %>
    <%= link_to 'トップページ', root_path, class:'link' %>
  <% else %>
    <%= link_to 'ログイン', top_main_path, class:'link' %>
    <%= link_to 'ユーザ一登録', new_user_path, class:'link' %>
  <% end %>
  </p>
  </body>
  </div>
  </header>
</html>

<h1>投稿</h1>
<%= form_with(model: @cafe, local: true) do |f| %>
    <div class="actions">
      <%= f.label :lat,"緯度" %>
      <%= f.text_field :lat,:value =>"緯度", id: :lat %>
      <%= f.label :lng,"経度" %>
      <%= f.text_field :lng,:value =>"経度", id: :lng %>
      <%= f.submit %>
    </div>
  <% end %>
  
  <h2>Map</h2>
  
  <input id="address" type="textbox" value="GeekSalon">
  <input type="button" value="検索" onclick="codeAddress()">
  <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
  <div id='map'></div>
  
  <style>
  #map {
    height: 600px;
    width: 600px;
  }
  </style>
  
  <script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()
  
    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: 35.6803997, lng:139.7690174},  //東京
      zoom: 15,
      
    });
  }
  
  //検索後のマップ作成
  let geocoder
  let aft
  function codeAddress(){
    let inputAddress = document.getElementById('address').value;
    geocoder.geocode( { 'address': inputAddress}, function(results, status) {
      if (status == 'OK') {
          //マーカーが複数できないようにする
          if (aft == true){
              marker.setMap(null);
          }
  
          //新しくマーカーを作成する
          map.setCenter(results[0].geometry.location);
              marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location,
              draggable: true	// ドラッグ可能にする
          });
  
          //二度目以降か判断
          aft = true
  
          //検索した時に緯度経度を入力する
          document.getElementById('lat').value = results[0].geometry.location.lat();
          document.getElementById('lng').value = results[0].geometry.location.lng();
  
          // マーカーのドロップ（ドラッグ終了）時のイベント
          google.maps.event.addListener( marker, 'dragend', function(ev){
              // イベントの引数evの、プロパティ.latLngが緯度経度
              document.getElementById('lat').value = ev.latLng.lat();
              document.getElementById('lng').value = ev.latLng.lng();
          });
      } else {
        alert('該当する結果がありませんでした：' + status);
      }
    });   
  }
  
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDzRgqwurGkhMDhatqXGPATnE8WZLb5aCY&callback=initMap" async defer></script>

<%= form_for @cafe, url:{action: :create} do |f| %>
<p>
  <%= f.label :name, '店名' %>
  <%= f.text_field :name %>
<br>
  <%= f.label :message, '説明' %>
  <%= f.text_area :message,:size=>"60x10" %>
<br>
  <%= f.label :image,'画像' %>
  <%= f.file_field :image %>


  <!--タグ付け機能-->
  <div class='form-group'>
       <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |tag| %>
          <div class='form-check'>
              <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
              <% end %>
          </div>
      <% end %>
  </div>


 <%= f.submit "投稿"%>
<% end %>

<%= link_to "戻る", :back %>

app/views/cafes/show.html.erb
<!DOCTYPE html>
<html>
  <header>
  	<h1 class="headline">
      <a>cafe巡り</a>
    </h1>
  <div class="right">
  <body>
  <p class='login'>
  <% if session[:login_uid] %>
    <%= link_to 'ログアウト', top_logout_path, class:'link' %>
    <%= link_to '投稿する', new_cafe_path, class:'link' %>
    <%= link_to 'マイページ', cafes_show_path, class:'link' %>
    <%= link_to 'トップページ', root_path, class:'link' %>
  <% else %>
    <%= link_to 'ログイン', top_main_path, class:'link' %>
    <%= link_to 'ユーザ一登録', new_user_path, class:'link' %>
  <% end %>
  </p>
  </body>
  </div>
  </header>
</html>

<h1 class="font-weight-normal mt-3">mypage</h1>
<% @cafe.each do |f| %>
<p>
  <font size="5">店名：<%= f.name %></font>
<br>
  <font size="5">コメント：<%= f.message %></font>
<br>
  <%= image_tag "/get_image/#{f.id}",class:'icon' %>
<br>

  <%= link_to '編集', edit_cafe_path(f.id), class:'link' %>
  <%= link_to '削除', cafe_path(f.id), method: :delete,class:'link' %>
</p>
<% end %>


<%= link_to "戻る", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafemeguri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<%= form_tag top_login_path, method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %> 
  <%= text_field_tag :uid %> 
  <%= label_tag :pass, 'パスワード' %> 
  <%= password_field_tag :pass %> 
  <%= submit_tag 'ログインする' %>
<% end %>

app/views/top/main.html.erb
ログイン中だよ！

<%= link_to "ログアウト", "top/logout" %>

<%= link_to "投稿する","cafes/new" %>

app/views/top/mypage.html.erb
<h1>マイページ</h1>
<% @cafes.each do |f| %>
<p>
  <% Cafe.find(f.id).name %>
<br>
  <% Cafe.find(f.id).message %>
<br>
  <%= image_tag "/get_image/#{f.id}" %>
<br>
  <%= link_to '編集', edit_cafe_path(f.id), class:'link' %>
  <%= link_to '削除', cafe_path(f.id), method: :destroy, class:'link' %>
</p>
<% end %>

<h1>マイページ</h1>
<% @cafe.each do |f| %>
<p>
  <% Cafe.find(f.id).name %>
<br>
  <% Cafe.find(f.id).message %>
<br>
  <%= image_tag "/get_image/#{f.id}" %>
<br>
  <%= link_to '編集', edit_cafe_path(f.id), class:'link' %>
  <%= link_to '削除', cafe_path(f.id), method: :delete,class:'link' %>
</p>
<% end %>

app/views/top/top.html.erb
<!DOCTYPE html>
<html>
  <header>
  	<h1 class="headline">
      <a>cafe巡り</a>
    </h1>
  <div class="right">
  <body>
  <p class='login'>
  <% if session[:login_uid] %>
    <%= link_to 'ログアウト', top_logout_path, class:'link' %>
    <%= link_to '投稿する', new_cafe_path, class:'link' %>
    <%= link_to 'マイページ', cafes_show_path, class:'link' %>
    <%= link_to 'トップページ', root_path, class:'link' %>
  <% else %>
    <%= link_to 'ログイン', top_main_path, class:'link' %>
    <%= link_to 'ユーザ一登録', new_user_path, class:'link' %>
  <% end %>
  </p>
  </body>
  </div>
  </header>
</html>

<%= form_tag cafes_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み検索',
                       onchange: 'submit(this.form);'
                     }
      %>
<% end %>


<div class="cover-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">カフェ投稿一覧</h1>
    </div>
    <div class="row justify-content-center">
      <% @cafe.each do |f| %>
      <p>
         <font size="5">店名:<%= f.name %></font>
        <br>
       <font size="5">コメント:<%= f.message %></font>
      　<br>
          <%= image_tag "/get_image/#{f.id}",class:'icon' %>
        <br>
      <% end %>
      </p>
     </div>
    </div>
  </div>
</div>
<
      

app/views/user/index.html.erb
<% @users.each do |e| %>
  <p>
    <%= e.uid %>
    <%= e.pass %>
    <%= link_to '削除', user_path(e), method: :delete %>
    </p>
<% end %>

<p>
  <%= link_to '新規ユーザ追加', new_user_path %>
</p>
</p>

app/views/user/new.html.erb
<%= form_for @user, url: {action: :create} do |f| %>
  <%= f.label :uid, 'ユーザーID' %> 
  <%= f.text_field :uid %> 
  <p>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit '登録' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
    <p>
    <%= e.uid %>
    <%= e.pass %>
    <%= link_to '削除', user_path(e), method: :delete %>
    </p>
<% end %>

<p>
  <%= link_to 'top', root_path, class:'link' %>
</p>

app/views/users/new.html.erb
<%= form_for @user, url: {action: :create} do |f| %>

 <div class="set_center_outer">
    <div class="set_center_inner">
  <%= f.label :uid, 'ユーザーID' %> 
  <%= f.text_field :uid %> 
  <p>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit '登録',class:'link' %>
    </div>
  </div>
  

<% end %>